### ISSUE TITLE
No module named 'tree_utils'

### ISSUE THREAD

**Issue by ianvalenca** [alvinxhan/Phydelity#7]
I`m getting this error, can anyone help me? thanks

> (base) C:\Users\iannunes\Documents\Phydelity-master>phydelity.py --tree C:\Users\iannunes\Tree.newick
> Traceback (most recent call last):
>   File "C:\Users\iannunes\miniconda3\Scripts\phydelity.py", line 4, in <module>
>     __import__('pkg_resources').run_script('Phydelity==2.0', 'phydelity.py')
>   File "C:\Users\iannunes\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 665, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "C:\Users\iannunes\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 1463, in run_script
>     exec(code, namespace, namespace)
>   File "c:\users\iannunes\miniconda3\lib\site-packages\phydelity-2.0-py3.6-win-amd64.egg\EGG-INFO\scripts\phydelity.py", line 16, in <module>
>     from phyilpd import node_leaves_reassociation, clean_up_modules, phydelity_output
>   File "C:\Users\iannunes\miniconda3\lib\site-packages\phydelity-2.0-py3.6-win-amd64.egg\phyilpd\__init__.py", line 1, in <module>
>     from tree_utils import clean_up_modules, node_leaves_reassociation
> ModuleNotFoundError: No module named 'tree_utils'

**Comment by ianvalenca** [comment]
Actually it was due to my my python version.
