### ISSUE TITLE
Output error - IOError

### ISSUE THREAD

**Issue by ianvalenca** [alvinxhan/Phydelity#8]
```
> Cleaning up clusters...
> Subsuming cluster-size sensitivity-induced subclusters <= 2 taxa (if any)...
> 
> Writing outputs...
> Traceback (most recent call last):
>   File "C:\Users\iannunes\miniconda3\envs\python2\Scripts\phydelity.py", line 4, in <module>
>     __import__('pkg_resources').run_script('Phydelity==2.0', 'phydelity.py')
>   File "C:\Users\iannunes\miniconda3\envs\python2\lib\site-packages\pkg_resources\__init__.py", line 666, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "C:\Users\iannunes\miniconda3\envs\python2\lib\site-packages\pkg_resources\__init__.py", line 1469, in run_script
>     exec(script_code, namespace, namespace)
>   File "C:\Users\iannunes\miniconda3\envs\python2\lib\site-packages\phydelity-2.0-py2.7-win-amd64.egg\EGG-INFO\scripts\phydelity.py", line 398, in <module>
> 
>   File "build\bdist.win-amd64\egg\phyilpd\output_utils.py", line 37, in cluster_output
> IOError: [Errno 2] No such file or directory: 'cluster_phydelity_k5_sol0_C:\\Users\\iannunes\\OneDrive\\Documentos\\Projeto_COVID_Campinas\\Analise_Campinas_Novas_Sequencias\\Campinas_Julho2020\\Tree.txt'
```

I have no clue how to solve this.

**Comment by ianvalenca** [comment]
I had to invert the ' \ ' symbol to '/ '  when defining the path to my newick Tree.
